repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ['gibberish-detector']